name: Build Dev Container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/.devcontainer/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "read"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare DevPod
        run: |
          curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" \
            && sudo install -c -m 0755 devpod /usr/local/bin \
            && rm -f devpod
          devpod provider add docker

      - name: Prebuild image
        run: |
          docker buildx ls
          devpod build . --devcontainer-path .github/.devcontainer/devcontainer.json \
            --repository "ghcr.io/${{ github.repository }}" \
            --platform linux/amd64,linux/arm64/v8,linux/arm/v7
          docker image ls
